# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Gearshift Workshop
email: bzwingzero@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A setting for Genesys
baseurl: "/Gearshift-Workshop" # the subpath of your site, e.g. /blog
url: "https://bzwingzero.github.io/Gearshift-Workshop/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: bzwingzero
# github_username:  bzwingzero

# Build settings
markdown: kramdown
# markdown: CommonMarkGhPages
theme: minima
plugins:
  - jekyll-feed

# Collections
collections:
  adversaries:
    collections_dir: _adversaries
    output: true
  campaigns:
    collections_dir: _campaigns
    output: true
  careers:
    collections_dir: _careers
    output: true
  equipment:
    collections_dir: _equipment
    output: true
  magic:
    collections_dir: _magic
    output: true
  races:
    collections_dir: _races
    output: true
  skills:
    collections_dir: _skills
    output: true
  talents:
    collections_dir: _talents
    output: true
  world:
    collections_dir: _world
    output: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
